repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.20
    hooks:
      - id: uv-lock
      - id: uv-export
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
