[project]
name = "flow-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.sources]
flow = { workspace = true }

[tool.uv.workspace]
members = ["flow"]

[dependency-groups]
dev = ["ipykernel>=6.29.5"]
