base:
  store: .store
  seed: 42

track:
  server:
    store: ${base.store}/${.name}
    uri: http://${.host}:${.port}
    host: 127.0.0.1
    name: mlflow
    port: 8080

train:
  epochs: 80
  augment: true

model:
  autoencoder:
    id: mit-han-lab/dc-ae-f32c32-sana-1.1-diffusers
    std: 2.3715
    mu: 0.1874

data:
  path: data
  preprocess:
    size: 512
    crop: "random"
