base:
  store: .store
  debug: false
  seed: 42

track:
  server:
    store: ${base.store}/${.name}
    uri: http://${.host}:${.port}
    host: 127.0.0.1
    name: mlflow
    port: 8080
  run:
    experiment: flow_matching
    name: train_run_001
    log_every: 1
    nest: null
    id: null

train:
  params:
    batch_size: 64
    epochs: null
    steps: null
    lr: 1e-4
  ckpt:
    resume: false
    name: ckpt
    dir: ckpt
    every: 1
  eval:
    split: 0.1
    every: 1

model:
  autoencoder:
    id: mit-han-lab/dc-ae-f32c32-sana-1.1-diffusers
    std: 2.3715
    mu: 0.1874
  vector_field:
    mlp_layers: 4
    n_class: 102
    out_dim: 32
    h_dim: 256
    h_size: 16
    w_size: 16
    in_dim: 32
    blocks: 20

data:
  path: data
  preprocess:
    augment: true
    crop: random
    norm: true
    size: 512
