base:
  store: .store

track:
  server:
    store: ${base.store}/${.name}
    uri: http://${.host}:${.port}
    host: 127.0.0.1
    name: mlflow
    port: 8080

train:
  epochs: 80

data:
  path: data
