path:
  root: .
  storage: ${.root}/.storage

log:
  server:
    uri: "http://${.host}:${.port}"
    path: ${path.storage}/mlflow
    host: 127.0.0.1
    port: 8080
  param:
    step_interval: 250
    sample_steps: 1000
    batch_size: 10

model:
  vae:
    repo: "stabilityai/sd-vae-ft-mse"
    scale: 0.19374
  flow:
    dim_in: 64
    dim_hidden: 256
    time_emb_dim: 128
    class_emb_dim: 128
    n_blocks: 4
    n_layers: 2
    num_groups: 32
    num_classes: 10

train:
  batch_size: 1024
  steps: 10000
  drop: 0.1
  lr: 1e-3

data:
  path: ${path.root}/data
