path:
  root: .
  storage: ${.root}/.storage

log:
  server:
    uri: "http://${.host}:${.port}"
    path: ${path.storage}/mlflow
    host: 127.0.0.1
    port: 8080

model:
  vae:
    repo: "stabilityai/sd-vae-ft-mse"
    scale: 0.19374

data:
  path: ${path.root}/data
